name: AutoTagRelease

on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: PIMPfiction/AutoTagVersionRelease@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}